### ISSUE TITLE
Make colors WCAG compliant by default

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-lumo-styles#22]
The current success color does not pass the contrast test. [We indicate that in the docs](https://cdn.vaadin.com/vaadin-lumo-styles/1.0.0-beta3/demo/colors.html#success), but it’s still poor service and bad service for users.

**Comment by vlukashov** [comment]
The `primary` color is not compliant either. It has the contrast ratio of 4.27 which is lower than 4.5 required by [WCAG 2.0 Level AA](https://www.w3.org/WAI/WCAG21/quickref/#contrast-minimum).

```css
:host([theme~="primary"]) {
  color: var(--lumo-primary-contrast-color);
  background-color: var(--lumo-primary-color);
}
```
